import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ProviderStore from './ProviderStore';
import CheckNavbar from './CheckNav';
import CheckFooter from './CheckFooter';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderStore>
        <body
          className={`${poppins.className} bg-custom-main4 overflow-x-hidden`}
        >
          <CheckNavbar />
          {children}
          <CheckFooter />
        </body>
      </ProviderStore>
    </html>
  );
}
